// ── Valheim meta (bundled fallback) ─────────────────────────
// Auto-generated by convert-dump.cjs — DO NOT EDIT. The live copy is
// /data/valheim-meta.json on the MegaWorker (publish-data.cjs).
import type { ValheimMeta } from "./valheimMeta";

export const BUNDLED_VALHEIM_META: ValheimMeta = {
  "schema": 1,
  "generated": "2026-10-02T19:30:07.350Z",
  "facets": [
    {
      "id": "itemClass",
      "title": "Class",
      "field": "itemClass",
      "values": [
        {
          "value": "Raw",
          "label": "Raw",
          "color": "#a3e635",
          "hint": "Gathered: mined, chopped, dropped, fished, picked or bought"
        },
        {
          "value": "Crafted",
          "label": "Crafted",
          "color": "#fbbf24",
          "hint": "Made by you, at a station or a factory"
        },
        {
          "value": "Item",
          "label": "Item",
          "color": "#60a5fa",
          "hint": "A finished thing you use: gear, pieces, meals, meads (Eyescream is Crafted and an Item)"
        }
      ]
    },
    {
      "id": "food",
      "title": "Food",
      "field": "food",
      "values": [
        {
          "value": "Ingredient",
          "label": "Ingredient",
          "color": "#fdba74",
          "hint": "Goes into another food, directly or through a step (Barley → Barley Flour → Bread)"
        },
        {
          "value": "Prep",
          "label": "Prep",
          "color": "#fbbf24",
          "hint": "Made only to cook or bake into something else (Barley Flour, Bread Dough, Uncooked dishes)"
        },
        {
          "value": "Eat as-is",
          "label": "Eat as-is",
          "color": "#86efac",
          "hint": "Food you can eat straight away (Bread, Deer Stew, Raspberries)"
        },
        {
          "value": "Feast",
          "label": "Feast",
          "color": "#f472b6",
          "hint": "Placed on a table and served to the group"
        }
      ]
    },
    {
      "id": "usedFor",
      "title": "Used For",
      "field": "usedFor",
      "values": [
        {
          "value": "Food",
          "label": "Food",
          "color": "#f97316"
        },
        {
          "value": "Meads & Potions",
          "label": "Meads & Potions",
          "color": "#c084fc"
        },
        {
          "value": "Gear",
          "label": "Gear",
          "color": "#94a3b8"
        },
        {
          "value": "Building",
          "label": "Building",
          "color": "#d6a35c"
        },
        {
          "value": "Fishing",
          "label": "Fishing",
          "color": "#38bdf8"
        },
        {
          "value": "Boss Summoning",
          "label": "Boss Summoning",
          "color": "#f87171"
        },
        {
          "value": "Taming",
          "label": "Taming",
          "color": "#34d399"
        }
      ]
    },
    {
      "id": "activity",
      "title": "Activity",
      "field": "tags",
      "values": [
        {
          "value": "Fishing",
          "label": "Fishing",
          "color": "#38bdf8",
          "hint": "Rod, baits and every fish"
        }
      ]
    }
  ],
  "rollup": {
    "oneOfRecipes": [
      "FishRaw"
    ],
    "excludeTags": [
      "Fishing"
    ]
  },
  "processingStations": [
    {
      "name": "Charcoal Kiln",
      "prefab": "charcoal_kiln",
      "description": "Converts wood into coal. Accepts regular wood and fine wood. Essential for fuelling smelters and blast furnaces.",
      "biome": "Black Forest",
      "conversions": [
        {
          "inputId": "Wood",
          "inputName": "Wood",
          "outputId": "Coal",
          "outputName": "Coal"
        },
        {
          "inputId": "FineWood",
          "inputName": "Finewood",
          "outputId": "Coal",
          "outputName": "Coal"
        },
        {
          "inputId": "RoundLog",
          "inputName": "Corewood",
          "outputId": "Coal",
          "outputName": "Coal"
        }
      ],
      "icon": "charcoal_kiln"
    },
    {
      "name": "Smelter",
      "prefab": "smelter",
      "description": "Smelts basic ores into metal bars using coal as fuel. Processes copper, tin, iron, and silver ores.",
      "biome": "Black Forest",
      "fuels": [
        {
          "name": "Coal",
          "id": "Coal"
        }
      ],
      "conversions": [
        {
          "inputId": "CopperOre",
          "inputName": "Copper Ore",
          "outputId": "Copper",
          "outputName": "Copper"
        },
        {
          "inputId": "IronOre",
          "inputName": "Iron Ore",
          "outputId": "Iron",
          "outputName": "Iron"
        },
        {
          "inputId": "IronScrap",
          "inputName": "Scrap Iron",
          "outputId": "Iron",
          "outputName": "Iron"
        },
        {
          "inputId": "BronzeScrap",
          "inputName": "Scrap Bronze",
          "outputId": "Bronze",
          "outputName": "Bronze"
        },
        {
          "inputId": "TinOre",
          "inputName": "Tin Ore",
          "outputId": "Tin",
          "outputName": "Tin"
        },
        {
          "inputId": "SilverOre",
          "inputName": "Silver Ore",
          "outputId": "Silver",
          "outputName": "Silver"
        },
        {
          "inputId": "CopperScrap",
          "inputName": "Copper Scrap",
          "outputId": "Copper",
          "outputName": "Copper"
        }
      ],
      "icon": "smelter"
    },
    {
      "name": "Blast Furnace",
      "prefab": "blastfurnace",
      "description": "An advanced furnace that smelts high-tier ores. Processes black metal scraps and flametal ore using coal.",
      "biome": "Plains",
      "fuels": [
        {
          "name": "Coal",
          "id": "Coal"
        }
      ],
      "conversions": [
        {
          "inputId": "FlametalOreNew",
          "inputName": "Flametal Ore",
          "outputId": "FlametalNew",
          "outputName": "Flametal"
        },
        {
          "inputId": "BlackMetalScrap",
          "inputName": "Black Metal Scrap",
          "outputId": "BlackMetal",
          "outputName": "Black Metal"
        },
        {
          "inputId": "GoldOre",
          "inputName": "Petrified Tissue",
          "outputId": "Gold",
          "outputName": "Bloodgold"
        }
      ],
      "icon": "blastfurnace"
    },
    {
      "name": "Spinning Wheel",
      "prefab": "piece_spinningwheel",
      "description": "Spins raw flax into linen thread. Required for crafting padded armour and some Plains-tier gear.",
      "biome": "Plains",
      "conversions": [
        {
          "inputId": "Flax",
          "inputName": "Flax",
          "outputId": "LinenThread",
          "outputName": "Linen Thread"
        }
      ],
      "icon": "piece_spinningwheel"
    },
    {
      "name": "Windmill",
      "prefab": "windmill",
      "description": "Grinds barley into barley flour. Must be placed outdoors with wind exposure to function.",
      "biome": "Plains",
      "conversions": [
        {
          "inputId": "Barley",
          "inputName": "Barley",
          "outputId": "BarleyFlour",
          "outputName": "Barley Flour"
        },
        {
          "inputId": "OatSeeds",
          "inputName": "Oat Seeds",
          "outputId": "Oat",
          "outputName": "Oats"
        },
        {
          "inputId": "Oat",
          "inputName": "Oats",
          "outputId": "OatFlour",
          "outputName": "Oat Flour"
        }
      ],
      "icon": "windmill"
    },
    {
      "name": "Eitr Refinery",
      "prefab": "eitrrefinery",
      "description": "Refines soft tissue and sap into refined Eitr — the magical essence needed for Mistlands-tier staffs and gear.",
      "biome": "Mistlands",
      "conversions": [
        {
          "inputId": "Softtissue",
          "inputName": "Soft Tissue",
          "outputId": "Eitr",
          "outputName": "Refined Eitr"
        }
      ],
      "icon": "eitrrefinery",
      "fuels": [
        {
          "name": "Sap",
          "id": "Sap"
        }
      ]
    },
    {
      "name": "Frost Foundry",
      "prefab": "piece_FrostFoundry",
      "description": "Deep North foundry that casts Bloodgold gear. Craft a Cast at the Black Forge from Bloodgold, Timberwood and the matching Mould, then let the foundry turn it into the finished Nord weapon, shield, armour or Intricate Key. Burns Liquid Frost.",
      "biome": "Deep North",
      "conversions": [
        {
          "inputId": "SwordGoldUncooked",
          "inputName": "Cast: Nord Sword",
          "outputId": "SwordGold",
          "outputName": "Nord Sword"
        },
        {
          "inputId": "AtgeirGoldUncooked",
          "inputName": "Cast: Nord Atgeir",
          "outputId": "AtgeirGold",
          "outputName": "Nord Atgeir"
        },
        {
          "inputId": "BattleaxeGoldUncooked",
          "inputName": "Cast: Nord Greataxe",
          "outputId": "BattleaxeGold",
          "outputName": "Nord Greataxe"
        },
        {
          "inputId": "AxeGoldUncooked",
          "inputName": "Cast: Nord Axe",
          "outputId": "AxeGold",
          "outputName": "Nord Axe"
        },
        {
          "inputId": "BowGoldUncooked",
          "inputName": "Cast: Nord Bow",
          "outputId": "BowGold",
          "outputName": "Nord Bow"
        },
        {
          "inputId": "CrossbowGoldUncooked",
          "inputName": "Cast: Nord Crossbow",
          "outputId": "CrossbowGold",
          "outputName": "Nord Crossbow"
        },
        {
          "inputId": "FistGoldUncooked",
          "inputName": "Cast: Nord Knucklechains",
          "outputId": "FistGold",
          "outputName": "Nord Knucklechains"
        },
        {
          "inputId": "KnifeGoldUncooked",
          "inputName": "Cast: Nord Dagger",
          "outputId": "KnifeGold",
          "outputName": "Nord Dagger"
        },
        {
          "inputId": "SledgeGoldUncooked",
          "inputName": "Cast: Nord Sledge",
          "outputId": "SledgeGold",
          "outputName": "Nord Sledge"
        },
        {
          "inputId": "MaceGoldUncooked",
          "inputName": "Cast: Nord Mace",
          "outputId": "MaceGold",
          "outputName": "Nord Mace"
        },
        {
          "inputId": "SpearGoldUncooked",
          "inputName": "Cast: Nord Spear",
          "outputId": "SpearGold",
          "outputName": "Nord Spear"
        },
        {
          "inputId": "THSwordGoldUncooked",
          "inputName": "Cast: Nord Greatsword",
          "outputId": "THSwordGold",
          "outputName": "Nord Greatsword"
        },
        {
          "inputId": "ArmorGoldHeavyChestUncooked",
          "inputName": "Cast: Breastplate of the Protector",
          "outputId": "ArmorDeepNorthHeavyChest",
          "outputName": "Breastplate of the Protector"
        },
        {
          "inputId": "ArmorGoldHeavyLegsUncooked",
          "inputName": "Cast: Trousers of the Protector",
          "outputId": "ArmorDeepNorthHeavylegs",
          "outputName": "Trousers of the Protector"
        },
        {
          "inputId": "ArmorGoldHeavyHelmetUncooked",
          "inputName": "Cast: Helmet of the Protector",
          "outputId": "HelmetDNHeavy",
          "outputName": "Helmet of the Protector"
        },
        {
          "inputId": "ArmorGoldMediumHelmetUncooked",
          "inputName": "Cast: Hood of the Vanguard",
          "outputId": "HelmetDNMediumHood",
          "outputName": "Hood of the Vanguard"
        },
        {
          "inputId": "ArmorGoldMediumChestUncooked",
          "inputName": "Cast: Chestpiece of the Vanguard",
          "outputId": "ArmorDeepNorthMediumChest",
          "outputName": "Chestpiece of the Vanguard"
        },
        {
          "inputId": "ArmorGoldMediumLegsUncooked",
          "inputName": "Cast: Trousers of the Vanguard",
          "outputId": "ArmorDeepNorthMediumlegs",
          "outputName": "Trousers of the Vanguard"
        },
        {
          "inputId": "ArmorGoldMageLegsUncooked",
          "inputName": "Cast: Trousers of the Caller",
          "outputId": "ArmorDeepNorthMagelegs",
          "outputName": "Trousers of the Caller"
        },
        {
          "inputId": "ArmorGoldMageChestUncooked",
          "inputName": "Cast: Robes of the Caller",
          "outputId": "ArmorDeepNorthMageChest",
          "outputName": "Robes of the Caller"
        },
        {
          "inputId": "ArmorGoldMageHelmetUncooked",
          "inputName": "Cast: Headdress of the Caller",
          "outputId": "HelmetDNMage",
          "outputName": "Headdress of the Caller"
        },
        {
          "inputId": "ShieldBucklerGoldUncooked",
          "inputName": "Cast: Nord Buckler",
          "outputId": "ShieldGoldBuckler",
          "outputName": "Nord Buckler"
        },
        {
          "inputId": "ShieldRoundGoldUncooked",
          "inputName": "Cast: Nord Shield",
          "outputId": "ShieldGold",
          "outputName": "Nord Shield"
        },
        {
          "inputId": "ShieldTowerGoldUncooked",
          "inputName": "Cast: Nord Greatshield",
          "outputId": "ShieldGoldTower",
          "outputName": "Nord Greatshield"
        },
        {
          "inputId": "KeysGoldUncooked",
          "inputName": "Cast: Intricate Key",
          "outputId": "BloodGoldKey",
          "outputName": "Intricate Key"
        },
        {
          "inputId": "StaffSpiritCallerUncooked",
          "inputName": "Cast: Spirit Caller",
          "outputId": "StaffSpiritCaller",
          "outputName": "Spirit Caller"
        },
        {
          "inputId": "StaffOrbofAhriUncooked",
          "inputName": "Cast: Echo Spike",
          "outputId": "StaffOrbofAhri",
          "outputName": "Echo Spike"
        },
        {
          "inputId": "StaffFrostOrbsUncooked",
          "inputName": "Cast: Northern Vengeance",
          "outputId": "StaffFrostOrbs",
          "outputName": "Northern Vengeance"
        },
        {
          "inputId": "StaffThunderbloodUncooked",
          "inputName": "Cast: Lightning Strike",
          "outputId": "StaffThunderBlood",
          "outputName": "Lightning Strike"
        }
      ],
      "icon": "piece_FrostFoundry",
      "fuels": [
        {
          "name": "Liquid Frost",
          "id": "FrozenFuel"
        }
      ]
    },
    {
      "name": "Shield Generator",
      "prefab": "piece_shieldgenerator",
      "description": "Creates a protective shield against weather and projectiles. Fuelled by bones — consumes Bone Fragments or Charred Bones to maintain its barrier.",
      "biome": "Mistlands",
      "fuels": [
        {
          "name": "Bone Fragments",
          "id": "BoneFragments"
        },
        {
          "name": "Charred Bones",
          "id": "CharredBone"
        }
      ],
      "conversions": [],
      "icon": "piece_shieldgenerator"
    },
    {
      "name": "Ballista",
      "prefab": "piece_turret",
      "description": "Automated defensive turret that fires missiles at hostile targets. Must be loaded with turret missiles — available in wood, black metal, and flametal variants.",
      "biome": "Mistlands",
      "conversions": [
        {
          "inputId": "TurretBoltWood",
          "inputName": "Wooden Missile",
          "outputId": "TurretBoltWood",
          "outputName": "Wooden Missile"
        },
        {
          "inputId": "TurretBolt",
          "inputName": "Black Metal Missile",
          "outputId": "TurretBolt",
          "outputName": "Black Metal Missile"
        },
        {
          "inputId": "TurretBoltFlametal",
          "inputName": "Flametal Missile",
          "outputId": "TurretBoltFlametal",
          "outputName": "Flametal Missile"
        }
      ],
      "icon": "piece_turret"
    }
  ]
};
