// ── Runtime hot-swap support for VALHEIM_ITEMS ────────────────
// `valheim-items.ts` is generated by convert-dump.cjs and bundled with the
// installer. When a fresh dataset arrives from the MegaWorker (see
// commands/valheim_data.rs + lib/valheimDataLoader.ts), we mutate the
// already-exported array and lookup maps IN PLACE so every consumer that
// holds a reference picks up the new data without re-importing.
//
// React re-renders are driven separately by the `dataVersion` counter in
// `stores/valheimDataStore.ts` — components that need to refresh on a swap
// subscribe to it via `useDataVersion()`.

import { VALHEIM_ITEMS, itemMap, tokenMap, type ValheimItem } from "./valheim-items";

/**
 * Replace the bundled dataset with a freshly-fetched one. Mutates the array
 * + maps in place so existing references stay valid. Rebuilds the prefab-id
 * and lowercase-token lookup maps to match.
 */
export function replaceValheimItems(items: ValheimItem[]): void {
  // Bail on empty input — refusing to overwrite a good dataset with []
  // mirrors the worker-side guard in routes/data.ts.
  if (!Array.isArray(items) || items.length === 0) return;

  // In-place mutation: keep the same array identity so chartStore/etc.
  // references stay valid.
  VALHEIM_ITEMS.length = 0;
  VALHEIM_ITEMS.push(...items);

  itemMap.clear();
  tokenMap.clear();
  for (const item of items) {
    itemMap.set(item.id, item);
    if (item.token) tokenMap.set(item.token.toLowerCase(), item);
  }
}
